name: 'jit'
services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/k6
    command: run /k6/sample.js
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    volumes:
      - ./zap:/zap/wrk:rw
    tty: true
    stdin_open: true
    user: "zap"

  nuclei:
    image: projectdiscovery/nuclei:latest
    volumes:
      - ./nuclei:/results
    entrypoint: ["nuclei"]
    command: ["-u", "https://umaxica.com/", "-o", "/results/report.txt"]

  lighthouse:
    image: femtopixel/google-lighthouse:latest
    volumes:
      - ./lighthouse:/lighthouse
    entrypoint: ["lighthouse"]
    command:
      - "https://umaxica.com/"
      - "--output=html,json"
      - "--output-path=/lighthouse/report"
      - "--chrome-flags=--no-sandbox --headless"

volumes:
  influxdb-data:
  grafana-data:
